.\" %%%LICENSE_START(APACHE_V2)
.\"
.\" Copyright (C) 2013 - present by OpenGamma Inc. and the OpenGamma group of companies
.\"
.\" Please see distribution for license.
.\"
.\" %%%LICENSE_END

.TH vd_pow3o2 3  "15 Jul 2014" "version 0.1"
.SH NAME
vd_pow3o2 - vectorised version of the operation, out0 := power(arg0,3/2).
.SH SYNOPSIS
.B #include <libizy/izy.h>
.sp
.BI "void vd_pow3o2(const int * "count
.BI ", const double * "arg0
.BI ", const int * "offsetarg0
.BI ", double * "out0
.BI ", const int * "offsetout0
.B ");"


Link with e.g. \fI\-lizy_std\fP.
.SH DESCRIPTION
The 
.BR vd_pow3o2 ()
function provides a vectorised version of the operation 
.B out0 := power(arg0,3/2)

.HP
.B Input:

.B "const int * count"
is the number of elements to process

.B "const double * arg0"
is the argument to be presented element wise to pow3o2()

.B "const int * offsetarg0"
is the offset into arg0 at which values should be taken

.B "const int * offsetout0"
is the offset into out0 at which values should be placed

.HP
.BR Output:

.B "double * out0"
contains the result of performing element wise power(arg0,3/2)

.PP
.SH EXAMPLE
.nf
/* Link with e.g. "\-lizy_std \-lm" */
#include <libizy/izy.h>
#include <stdio.h>
#include <complex.h>
#include <math.h>
int main()
{
  int i;
  int n = 4;
  static double in_data[] = {0.1, 0.2, 0.3, 0.4 };
  double results_data[n];

  const int offsetin0 = 0;
  const int offsetout0 = 0;
  const int count = n;

  /* make izy call */
  vd_pow3o2(&count, in_data, &offsetin0, results_data, &offsetout0);

  /* check */
  printf("vd_pow3o2():\\n");
  printf(" Input  | Output | Calling power(in_data[i],3/2)\\n");
  for(i=0; i<n; i++)
    {
      printf("%6.3f   %6.3f   %6.3f\\n", in_data[i], results_data[i], power(in_data[i],3/2));
    }
}
.fi
.SH AUTHOR
OpenGamma Inc. and the OpenGamma group of companies.
.SH "SEE ALSO"
.B power(3), vd_pow(3), vd_powx(3), vz_pow(3)
