.TH vz_negatereal 3  "20 Mar 2013" "version 0.1"
.SH NAME
vz_negatereal - vectorised version of the operation, out0 := -real(arg0)+I*imag(arg0) 
for complex arg0
.
.SH SYNOPSIS
.B #include <libizy/izy.h>
.sp
.BI "void vz_negatereal(const int * "count
.BI ", const complex double * "arg0
.BI ", const int * "offsetarg0
.BI ", complex double * "out0
.BI ", const int * "offsetout0
.B ");"


Link with \fI\-lizy\fP.
.SH DESCRIPTION
The 
.BR vz_negatereal ()
function provides a vectorised version of the operation 
.B out0 := -real(arg0)+I*imag(arg0)
for complex arg0.

.HP
.B Input:

.B "const int * count"
is the number of elements to process

.B "const complex double * arg0"
is the argument to be presented element wise to negatereal()

.B "const int * offsetarg0"
is the offset into arg0 at which values should be taken

.B "const int * offsetout0"
is the offset into out0 at which values should be placed

.HP
.BR Output:

.B "complex double * out0"
contains the result of performing element wise -real(arg0)+I*imag(arg0)

.PP
.SH EXAMPLE
.nf
/* Link with "\-lizy \-lm" */
#include <libizy/izy.h>
#include <stdio.h>
#include <complex.h>
#include <math.h>
int main()
{
  int i;
  int n = 4;
  static complex double in_data[] = {0.1 + 0.2*I, 0.2+0.3*I, 0.3+0.4*I, 0.4+0.5*I };
  complex double results_data[n];

  const int offsetin0 = 0;
  const int offsetout0 = 0;
  const int count = n;

  /* make izy call */
  vz_negatereal(&count, in_data, &offsetin0, results_data, &offsetout0);

  /* check */
  printf("vz_negatereal():\\n");
  printf(" Input  | Output | Calling -creal(in_data[i])+I*cimag(in_data[i])\\n");
  for(i=0; i<n; i++)
    {
      printf("%6.3f+%6.3fi   %6.3f+%6.3fi     %6.3f+%6.3fi\\n", creal(in_data[i]), cimag(in_data[i]), creal(results_data[i]), cimag(results_data[i]), creal(-creal(in_data[i])+I*cimag(in_data[i])), cimag(-creal(in_data[i])+I*cimag(in_data[i])));
    }
}
.fi
.SH AUTHOR
Stuart Archibald (stuart (at) opengamma.com)
.SH "SEE ALSO"
.B conj(3), vz_conj(3), vz_negate(3)
